### ISSUE TITLE
how to read faster

### ISSUE THREAD

**Issue by PythonShell** [olemb/dbfread#19]
Many thanks to the dbfread package, it saves my time. But now, it consume lots time of my computer :-) 

The API I use is:
```
for record in DBF(filepath):
    # something really simple
```

I waste lots of time on reading the file, about 1 minute, the dbf have approximate 12 MB

How can I read it faster?

If I am concerned about the incremental part, how can i read them?

thank you in advance!

**Comment by olemb** [comment]
I've done all I could think of to make dbfread fast but unfortunately it has to do a lot of processing for each record.

One thing you could try is to use dictionaries instead of OrderedDict:

```
for record in DBF(filepath, recfactory=dict):
    ...
```

dbfread uses OrderedDict as default for convenience, but this adds some overhead.

Passing `recfactory=None` will give you `(name, value)` tuples which should be even faster but probably harder to work with.

Depending on your data you could read the file in raw mode and decode the byte strings yourself. This would save a lot of decoding if you're only using some of the fields:

```
for record in DBF(filepath, raw=True):
    name = record['name'].decode('latin1')
    age = int(record['age'])
```

Passing `lowernames=False` could help a tiny bit as it would save a call to `.lower()`.

I'll see if I can think of anything else.

**Comment by PythonShell** [comment]
Thanks for the advices!

**Comment by PythonShell** [comment]
Hi, I have a mistake, most my time is consumed in the simple code, not in read dbf file.
I have changed the code inside for loop, and it speed up.
Sorry for the mistake and thank you very much for this module!

Maybe you can choose to close this issue. :-P

**Comment by olemb** [comment]
Ah, that's good news. I'll close the issue.
